**Name: Ajay Goyal**

**Roll No. 102303197**

**Assignment 1 (UCS547)**

In [2]:
import numpy as np

 Ques.1  Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) )

In [3]:
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]

print("Original array:", arr)
print("Reversed array:", reversed_arr)


Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]


Ques. 2. Compare the following numpy arrays: arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[1, 2], [3, 4]])

In [4]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

comparison = arr1 == arr2
are_equal = np.array_equal(arr1, arr2)

print("Element-wise comparison:\n", comparison)
print("Are both arrays completely equal?", are_equal)


Element-wise comparison:
 [[ True  True]
 [ True  True]]
Are both arrays completely equal? True


Ques.3 Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [5]:
# Q3(i): Most frequent value and indices in x
x = np.array([1,2,3,4,5,1,2,1,1,1])

values, counts = np.unique(x, return_counts=True)
most_frequent_value = values[np.argmax(counts)]
indices = np.where(x == most_frequent_value)

print("Array x:", x)
print("Most frequent value:", most_frequent_value)
print("Indices:", indices)


Array x: [1 2 3 4 5 1 2 1 1 1]
Most frequent value: 1
Indices: (array([0, 5, 7, 8, 9]),)


In [6]:
# Q3(ii): Most frequent value and indices in y
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)
most_frequent_value = values[np.argmax(counts)]
indices = np.where(y == most_frequent_value)

print("Array y:", y)
print("Most frequent value:", most_frequent_value)
print("Indices:", indices)


Array y: [1 1 1 2 3 4 2 4 3 3]
Most frequent value: 1
Indices: (array([0, 1, 2]),)


Ques.4. For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'),
find

i. Sum of all elements

ii. Sum of all element’s row-wise

iii. Sum of all element’s column-wise

In [7]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

# i. Sum of all elements
total_sum = gfg.sum()

# ii. Row-wise sum
row_wise_sum = gfg.sum(axis=1)

# iii. Column-wise sum
column_wise_sum = gfg.sum(axis=0)

print("Matrix:\n", gfg)
print("Sum of all elements:", total_sum)
print("Row-wise sum:\n", row_wise_sum)
print("Column-wise sum:\n", column_wise_sum)


Matrix:
 [[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
Sum of all elements: 45
Row-wise sum:
 [[14]
 [16]
 [15]]
Column-wise sum:
 [[20  9 16]]
